[build]
buildCommand = "pnpm run build:api"
watchPatterns = ["packages/api/**", "pnpm-lock.yaml"]

[deploy]
startCommand = "pnpm --filter api run start"
preDeployCommand = "pnpm run prisma:migrate:deploy"
